"""1

Revision ID: e8b999c59dfd
Revises: 
Create Date: 2022-03-31 14:21:33.181108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b999c59dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_name', sa.String(), nullable=True),
    sa.Column('running', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('world_map', sa.JSON(), nullable=True),
    sa.Column('grass_map', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('selected_island', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selected_island'], ['game_world.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_z', sa.Float(), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('saturation', sa.Float(), nullable=True),
    sa.Column('hydration', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('vision_radius', sa.Float(), nullable=True),
    sa.Column('hearing_radius', sa.Float(), nullable=True),
    sa.Column('prettiness', sa.Float(), nullable=True),
    sa.Column('attraction', sa.Float(), nullable=True),
    sa.Column('stealth', sa.Integer(), nullable=True),
    sa.Column('max_health', sa.Integer(), nullable=True),
    sa.Column('max_saturation', sa.Integer(), nullable=True),
    sa.Column('max_hydration', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('move_status', sa.Integer(), nullable=True),
    sa.Column('pet_type', sa.String(), nullable=True),
    sa.Column('race', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('skin', sa.JSON(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('move_log', sa.JSON(), nullable=True),
    sa.Column('change_move_status_timestamp', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['game_world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hard_token', sa.String(), nullable=True),
    sa.Column('soft_token', sa.String(), nullable=True),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soft_1', sa.Float(), nullable=True),
    sa.Column('soft_2', sa.Float(), nullable=True),
    sa.Column('pop_up_timestamp', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_table('token')
    op.drop_table('entity')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('game_world')
    # ### end Alembic commands ###
